spring:
  cloud:
    gateway:
      routes:
        - id: usuarios
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/health, /api/health
            - RewritePath=/api/usuarios/tipos?(?<segment>.*), /api/tipo-usuario$\{segment}
            - RewritePath=/api/usuarios?(?<segment>.*), /api/usuario$\{segment}
            - AuthFilter

        - id: auth
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/auth/**

        - id: productos
          uri: http://ms-productos:3000
          predicates:
            - Path=/api/productos/**
          filters:
            - RewritePath=/api/productos/health, /api/health
            - RewritePath=/api/productos/categorias/?(?<segment>.*), /api/categorias/$\{segment}
            - RewritePath=/api/productos/proveedores/?(?<segment>.*), /api/proveedores/$\{segment}
            - RewritePath=/api/productos/?(?<segment>.*), /api/productos/$\{segment}
            - AuthFilter

        - id: pedidos
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/api/pedidos/**
          filters:
            - RewritePath=/api/pedidos/health, /api/health
            - RewritePath=/api/pedidos?(?<segment>.*), /api/pedidos$\{segment}
            - AuthFilter
